services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_USER=${DB_UNAME}
    ports:
      - 5431:5432
    volumes:
      - ../GES-db:/var/lib/postgresql/data
    networks:
      - db

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PWD}
    networks:
      - db
      - pg

  spring:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${JDBC_DB}
      SPRING_DATASOURCE_USERNAME: ${DB_UNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PWD}
    networks:
      - db
      - spring

networks:
  db: {}
  pg: {}
  spring: {}